// ./app/layout.tsx

import '../styles/globals.css'
import { Vibur } from 'next/font/google'

const vb = Vibur({
  subsets: ["latin"],
  weight: "400"
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={vb.className}>{children}</body>
    </html>
  )
}
